Modeling users
sudobooo/to-do-insales pull request #5
Opened 2022-09-14 14:10 UTC by sudobooo

Обновил модель пользователя, добавил необходимые поля, в том числе пароль, и их валидацию.

2022-09-15 13:58 UTC, DanilShU requested changes

2022-09-15 13:58 UTC, DanilShU commented on app/models/user.rb
> +  VALID_PASSWORD_REGEX = /(?=.*[0-9])(?=.*[!@#$%^&*])(?=.*[a-z])(?=.*[A-Z])[0-9a-zA-Z!@#$%^&*]/
Странное ограничение, пароли в открытом виде в базе не хранят. Если по простому то пароли хэшируются, например при помощи алгоритма MD5. Затем Хэш записывают в базу и каждый раз при авторизации пользователя сравнивают хэш в базе и хэш пароля введенный пользователем.

2022-09-15 13:58 UTC, DanilShU commented on app/models/user.rb
> +  validates :password, presence: true, length: { minimum: 8 },
Размер строки после хэширования будет строго определенным, поэтому не обязательно это валидировать.

2022-09-16 10:32 UTC, sudobooo commented on app/models/user.rb
> +  VALID_PASSWORD_REGEX = /(?=.*[0-9])(?=.*[!@#$%^&*])(?=.*[a-z])(?=.*[A-Z])[0-9a-zA-Z!@#$%^&*]/
Ну они же в базе такими становятся уже — да, но ведь если пароль будет простым и таким сможет записаться в базу, то неважно будет к нему применена хэш-функция или нет, всё равно может простым перебором подобрать, проверяя самые простые пароли.

2022-09-16 10:36 UTC, sudobooo commented on app/models/user.rb
> +  validates :password, presence: true, length: { minimum: 8 },
Это я тоже добавил с позиции, что там любые пароли должны быть не меньше 8 символов, тип даже на этапе именно записи, чтобы человек не мог придумать лёгкий пароль.

2022-09-20 10:04 UTC, merged